# This will look for packages in install_files/ansible-base,
# so the "build" directory is relative to playbook, which is
# why the parent dirs ("..") are necessary.
- name: Copy locally built deb packages to server (Staging only).
  copy:
    src: ../../build/{{ item }}
    dest: /root/
  with_items: local_deb_packages

# Using `dpkg` via `command` rather than the `deb` parameter to the `apt`
# module to ensure installation every time, regardless of whether packages
# changed. SecureDrop deb package builds are not deterministic, so the `copy`
# task above will always report changed. Ignore version number in the control
# field and force installation every time.
- name: Install locally built deb packages.
  command: dpkg -i /root/{{ item }}
  with_items: local_deb_packages
